# Generated by Django 4.2.2 on 2023-07-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
