# Generated by Django 4.2.2 on 2023-08-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_parameter',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
