# Generated by Django 4.2.2 on 2023-08-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_add_image_parameter_field_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
