# Generated by Django 4.2.2 on 2023-08-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_remove_destination_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
