# Generated by Django 4.2.2 on 2023-08-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0009_alter_destination_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='slug',
        ),
    ]
