# Generated by Django 4.2.2 on 2023-07-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')])),
                ('average_temperature', models.FloatField()),
                ('highest_temperature', models.FloatField()),
                ('lowest_temperature', models.FloatField()),
                ('average_feels_like_temperature', models.FloatField()),
                ('highest_feels_like_temperature', models.FloatField()),
                ('lowest_feels_like_temperature', models.FloatField()),
                ('relative_humidity', models.FloatField()),
                ('heat_index', models.FloatField()),
                ('precipitation_levels', models.FloatField()),
                ('air_quality_index', models.FloatField()),
                ('cloud_cover', models.FloatField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.destination')),
            ],
        ),
    ]
